import { ReportStatus, RewardStatus, type Report, type Reward, type Site } from "~/types";

export const mockRewards: Reward[] = [
  {
    id: "rw1",
    reportId: "1",
    reportTitle: "낙하물 위험",
    siteId: "site1",
    siteName: "민이앤아이 1 현장",
    userId: "u12900iadr",
    amount: 100_000,
    status: RewardStatus.completed,
    date: new Date("2025-08-28"),
  },
  {
    id: "rw2",
    reportId: "2",
    reportTitle: "전기 안전 위험",
    siteId: "site2",
    siteName: "강변 아파트 단지",
    userId: "u21o32jsfdlk",
    amount: 70_000,
    status: RewardStatus.inProgress,
    date: new Date("2025-06-27"),
  },
  {
    id: "rw3",
    reportId: "3",
    reportTitle: "구조물 안전 위험",
    siteId: "site3",
    siteName: "고속도로 교량 프로젝트",
    userId: "u31opjawjfklasjlfk",
    amount: 120_000,
    status: RewardStatus.pending,
    date: new Date("2025-05-26"),
  },
];

export const mockSites: Site[] = [
  { id: "all", name: "전체 현장", location: "모든 현장", totalReports: 32 },
  {
    id: "site1",
    name: "민이앤아이 1 현장",
    location: "다운타운 메인가 123번지",
    totalReports: 9,
  },
  {
    id: "site2",
    name: "강변 아파트 단지",
    location: "리버사이드 강변로 456번지",
    totalReports: 8,
  },
  {
    id: "site3",
    name: "고속도로 교량 프로젝트",
    location: "15번 국도 42km 지점",
    totalReports: 7,
  },
  {
    id: "site4",
    name: "지하철역 확장 공사",
    location: "중앙역 광장",
    totalReports: 5,
  },
  {
    id: "site5",
    name: "쇼핑센터 리모델링",
    location: "상업대로 789번지",
    totalReports: 3,
  },
];

export const mockReports: Report[] = [
  {
    id: "1",
    siteName: "민이앤아이 1 현장",
    siteId: "site1",
    location: "다운타운 메인가 123번지",
    date: new Date("2025-08-28"),
    status: ReportStatus.completed,
    type: "낙하물 위험",
    description:
      "5층 작업장에서 안전망 미설치 및 낙하물 위험 발견, 즉시 조치 완료",
  },
  {
    id: "2",
    siteName: "강변 아파트 단지",
    siteId: "site2",
    location: "리버사이드 강변로 456번지",
    date: new Date("2025-06-27"),
    status: ReportStatus.inProgress,
    type: "전기 안전 위험",
    description: "지하 전기실 누수로 인한 감전 위험, 전기 안전 점검 진행 중",
  },
  {
    id: "3",
    siteName: "고속도로 교량 프로젝트",
    siteId: "site3",
    location: "15번 국도 42km 지점",
    date: new Date("2025-05-26"),
    status: ReportStatus.pending,
    type: "구조물 안전 위험",
    description:
      "임시 비계 불안정으로 인한 붕괴 위험, 구조 엔지니어 검토 대기 중",
  },
  {
    id: "4",
    siteName: "지하철역 확장 공사",
    siteId: "site4",
    location: "중앙역 광장",
    date: new Date("2025-03-25"),
    status: ReportStatus.completed,
    type: "화재 위험",
    description: "용접 작업 중 가연물 근접 화재 위험, 안전 구역 설정 완료",
  },
  {
    id: "5",
    siteName: "쇼핑센터 리모델링",
    siteId: "site5",
    location: "상업대로 789번지",
    date: new Date("2025-03-24"),
    status: ReportStatus.inProgress,
    type: "유해물질 노출",
    description: "석면 해체 작업 중 방진 마스크 미착용 발견, 안전교육 진행 중",
  },
  {
    id: "6",
    siteName: "민이앤아이 1 현장",
    siteId: "site1",
    location: "다운타운 메인가 123번지",
    date: new Date("2025-01-26"),
    status: ReportStatus.pending,
    type: "작업장 정리",
    description: "작업 도구 방치 및 통로 확보 필요",
  },
  {
    id: "7",
    siteName: "강변 아파트 단지",
    siteId: "site2",
    location: "리버사이드 강변로 456번지",
    date: new Date("2025-01-25"),
    status: ReportStatus.inProgress,
    type: "소음 문제",
    description: "야간 작업 소음 규정 위반, 작업시간 조정 완료",
  },
];
